- name: Create the Traefik network
  docker_network:
    name: ldap

- name: Create OpenLDAP folder
  ansible.builtin.file:
    path: "{{openldap_home}}"
    state: directory 

- name: Copy docker-compose.yaml.j2
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: "{{openldap_home}}/docker-compose.yaml"

- name: start openLDAP service
  community.general.docker_compose: 
    project_src: "{{openldap_home}}"